### ISSUE TITLE
 Kernel for sparse matrix purging (clique step 2)

### ISSUE THREAD

**Issue by remenska** [nlesc-km3net/KM3NeT#2]

**Comment by benvanwerkhoven** [comment]
This was implemented a while ago, see the kernels in: [remove_nodes.cu](https://github.com/benvanwerkhoven/KM3Net/blob/master/km3net/kernels/remove_nodes.cu) and [minimum_degree.cu](https://github.com/benvanwerkhoven/KM3Net/blob/master/km3net/kernels/minimum_degree.cu)

The whole of sparse matrix purging is implemented in three kernels:
 * remove_nodes removes the nodes that have a degree less than the minimum degree and removes edges to removed nodes from remaining nodes.
 * minimum_degree computes a block-wise minimum degree and number of remaining nodes
 * combine_blocked_min_num combines the block-wise minimum values and number of remaining nodes into single global values

The Python interface to calling these GPU kernels is implemented in [km3net/kernels.py](https://github.com/benvanwerkhoven/KM3Net/blob/master/km3net/kernels.py). The documentation on how to use the PurgingSparse object is located [here](https://benvanwerkhoven.github.io/KM3Net/sphinxdoc/html/internal.html#km3net-kernels-purgingsparse).
